FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir psycopg2-binary requests python-dotenv

COPY config/ ./config/
COPY scripts/data_generator.py ./scripts/

CMD ["python", "-u", "-m", "scripts.data_generator"]
